### PR TITLE
Reverse the render order

### LINKED ISSUE #7: Reverse the render order
Should the first component listed be the outermost?

---

**Libs with right-to-left as the only behavior or the default behavior:**

- Redux
- Apollo
- React Request (presently)

**Libs with left-to-right as the only behavior or the default behavior:**

- Lodash

### LINKED ISSUE #19: Add `functional` prop
`functional` would give developers more control over the `components`.

tl;dr, the result of each component is passed into the next. This would allow for async render prop components to work in series based off of the results of the previous component.

---

**Update** The name "serial" doesn't quite communicate how this works, because it doesn't enforce serial rendering, it just _enables_ it.

Here's an example of what the API might look like:

```jsx
<Composer functional components={[
    () => <RenderPropComponent {...configOne} />,
    (resultOne) => <RenderPropComponent {...configTwo} />,
    (resultOne, resultTwo) => <RenderPropComponent {...configThree} />
  ]}>
  {([resultOne, resultTwo, resultThree]) => (
    <MyComponent results={[resultOne, resultTwo, resultThree]} />
  )}
</Composer>
```

### PR DESCRIPTION
**Pull request by jmeas**
Resolves #7 

I thought I was being clever with the reverse render order, but I think it was a mistake in hindsight. This way makes more sense, especially in light of the changes made to resolve #19 .

//cc @erikthedeveloper 

Erik, I'll cut a release for this if you're :+1:

### CODE REVIEW

**Comment by malash** [comment]
Great work! Waiting for the PR been merged.

**Comment by jmeas** [comment]
your wish is my command!

**Comment by erikthedeveloper** [comment]
Oh whoops! 😳 It looks like I was ~20 minutes too late. My bad, I should have double checked this morning to see if you had already started on this @jmeas 

FWIW this is what I had put together I was just going to submit as PR for #7 when I saw this #33 https://github.com/jmeas/react-composer/compare/4952362acecdeede27f6da91bc03cda4463519fd...erikthedeveloper:reverse-render-order

I'll just dump this here.

> I thought I was being clever with the reverse render order

Haha, removing that did simplify things quite a bit 👍 

```js
/**
 * Recursively build up elements from props.components and accumulate `results` along the way.
 * @param next The first entry in components
 * @param ...remaining The remaining entries in components
 * @param results This is the argument that we pass into `children`
 * @returns {ReactElement}
 */
function chainComponents([next, ...remaining], results = []) {
  // When we reach the end of our `childrenComponents`, we can render out
  // the response array.
  if (!next) {
    return children(results);
  }

  // Each props.components entry is either an element or function [element factory]
  // When it is a function, produce an element by invoking it with currently accumulated results.
  const element = typeof next === 'function' ? next(results) : next;

  return React.cloneElement(element, {
    [renderPropName]() {
      return chainComponents(
        remaining,
        results.concat(mapResult ? [mapResult(...arguments)] : arguments[0])
      );
    }
  });
}

return chainComponents(components);
```

**Comment by jmeas** [comment]
Ah drat, sorry for misleading you into doing duplicate work @erikthedeveloper !

That's pretty clean looking, though. If the built version of that gzips down to a smaller size than the current implementation, then I'd love to swap that implementation in for what is currently in the source.

Want to check that out? (I typically use [`gzip-size-cli`](https://github.com/sindresorhus/gzip-size-cli) to compare the built versions.)

**Comment by erikthedeveloper** [comment]
@jmeas This is the first I've heard of `gzip-size-cli`. That is quite handy 😃 I just compared against `4.0.0` and mine is `24B` smaller at `500B` exactly 🙌 haha I guess every little byte counts. 

image

**Comment by jmeas** [comment]
> haha I guess every little byte counts.

It does. Let's swap it in.

**Comment by erikthedeveloper** [comment]
Got a PR submitting now! 🔥 Haha made sense while I had this all up and running

**Pull request merged**
